### ISSUE TITLE
add something in docs about polyfill need

### ISSUE THREAD

**Issue by btopro** [Glitch0011/intersection-observer-element#1]
Awesome element but it doesn't work correctly in Safari - http://caniuse.com/#search=intersection

Dave Walsh Blog points to this polyfill for anyone else that runs into this -- https://github.com/w3c/IntersectionObserver/tree/gh-pages/polyfill

**Comment by moritonal** [comment]
Many thanks @btopro, would you consider this closed?

**Comment by btopro** [comment]
sounds good, thx
