### ISSUE TITLE
how to use it for polymer version lower than 2.0.0?

### ISSUE THREAD

**Issue by gauravonly** [Glitch0011/intersection-observer-element#3]
@Glitch0011  -- I want to use it inside my pwa application which is currently using polymer's version of 1.8.0.???

**Comment by moritonal** [comment]
Hi @gauravkk22, I'm glad you'd like to use this. Whilst I'm unable to allocate any time into downgrading my element, it's a very simple element so you'd be able to copy large parts of it if you wished to port it yourself. You can see [this](https://www.polymer-project.org/2.0/docs/upgrade) link for advice on upgrading, which you can do the inverse of.

On the other hand, it might make more sense for you to upgrade your application instead, given you are likely to come across this problem more and more as you continue to use Web Components. Especially given 3.0 is almost upon us.

**Comment by gauravonly** [comment]
@Glitch0011 - - Thanks a lot :)
